# Generated by Django 4.2 on 2023-05-17 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_subject_studentmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentmark', to='vege.student'),
        ),
    ]
